# Generated by Django 6.0 on 2025-12-09 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoupleUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples', to='api.couple')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
